# Generated by Django 5.1.2 on 2024-11-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='isbn',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
